import type { MechanicDef, ObjectKind } from '../core/types';

const deg = (d: number) => (d * Math.PI) / 180;

export const CATALOG: Record<ObjectKind, MechanicDef> = {
  platform: {
    kind: 'platform',
    name: 'Platform',
    blurb: 'A firm surface. Balls settle here instead of sliding forever.',
    category: 'structure',
    w: 2.4,
    h: 0.28,
    rot: 0,
    props: {},
  },
  ramp: {
    kind: 'ramp',
    name: 'Ramp',
    blurb: 'A slick plank. The ball slides along it and keeps its speed.',
    category: 'structure',
    w: 3.2,
    h: 0.22,
    rot: deg(-15),
    props: {},
  },
  wall: {
    kind: 'wall',
    name: 'Wall',
    blurb: 'A tall stop. Use it to catch a ball or turn a path.',
    category: 'structure',
    w: 0.28,
    h: 2.4,
    rot: 0,
    props: {},
  },
  spring: {
    kind: 'spring',
    name: 'Spring',
    blurb: 'Stores energy, then throws the ball along its arrow at a fixed speed.',
    category: 'motion',
    w: 1.15,
    h: 0.5,
    rot: deg(90),
    props: { power: 12 },
  },
  bouncer: {
    kind: 'bouncer',
    name: 'Bouncer',
    blurb: 'Kicks the ball off its face. The stripe shows the kick.',
    category: 'motion',
    w: 1.35,
    h: 0.32,
    rot: 0,
    props: { power: 10 },
  },
  accelerator: {
    kind: 'accelerator',
    name: 'Accelerator',
    blurb: 'Adds speed along its arrows, up to a limit.',
    category: 'motion',
    w: 2,
    h: 1.15,
    rot: 0,
    props: { power: 28, max: 12 },
  },
  conveyor: {
    kind: 'conveyor',
    name: 'Conveyor',
    blurb: 'Drags the ball along the belt, even uphill.',
    category: 'motion',
    w: 2.8,
    h: 0.28,
    rot: 0,
    props: { power: 4 },
  },
  gravity: {
    kind: 'gravity',
    name: 'Gravity field',
    blurb: 'Replaces gravity inside the frame. The arrow is the new down.',
    category: 'field',
    w: 2.6,
    h: 3,
    rot: 0,
    props: { power: 20 },
  },
  portal: {
    kind: 'portal',
    name: 'Portal',
    blurb: 'A paired doorway. Enter one, leave the other, velocity turned to match.',
    category: 'routing',
    w: 0.42,
    h: 1.5,
    rot: 0,
    props: {},
  },
  cannon: {
    kind: 'cannon',
    name: 'Cannon',
    blurb: 'Swallows the ball and fires it along the barrel.',
    category: 'routing',
    w: 1.25,
    h: 0.62,
    rot: deg(60),
    props: { power: 15 },
  },
  switch: {
    kind: 'switch',
    name: 'Switch',
    blurb: 'Flips when the ball touches it, and stays flipped.',
    category: 'logic',
    w: 0.95,
    h: 0.7,
    rot: 0,
    props: {},
  },
  door: {
    kind: 'door',
    name: 'Door',
    blurb: 'A gate that opens when its switch flips.',
    category: 'logic',
    w: 0.28,
    h: 1.7,
    rot: 0,
    props: {},
  },
  mover: {
    kind: 'mover',
    name: 'Ferry',
    blurb: 'A platform that travels back and forth along its arrow.',
    category: 'motion',
    w: 2.2,
    h: 0.28,
    rot: 0,
    props: { distance: 3, period: 4 },
  },
  spinner: {
    kind: 'spinner',
    name: 'Wheel',
    blurb: 'A plank that turns. It can carry or fling the ball.',
    category: 'motion',
    w: 2.2,
    h: 0.24,
    rot: 0,
    props: { omega: 1.2 },
  },
  breakable: {
    kind: 'breakable',
    name: 'Fragile',
    blurb: 'Holds until a hard enough hit, then gives way.',
    category: 'structure',
    w: 1.6,
    h: 0.28,
    rot: 0,
    props: { threshold: 6 },
  },
  oneway: {
    kind: 'oneway',
    name: 'One-way shelf',
    blurb: 'The ball can pass upward, then rest on top. Chevrons show the pass.',
    category: 'routing',
    w: 1.8,
    h: 0.18,
    rot: 0,
    props: {},
  },
};

export const CATEGORY_LABEL: Record<MechanicDef['category'], string> = {
  structure: 'Structure',
  motion: 'Motion',
  field: 'Fields',
  routing: 'Routing',
  logic: 'Logic',
};
